### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by vdanelia**
Changes made in Modules.Class.php, Modules and lang

### CODE REVIEW

**Comment by vdanelia** [comment]
Semplon I'm using NotePad ++ I have set tab to 4 spaces what I'm dong incorrectly can you show me a screenshot what i'm doing wrong
Thanks

**Comment by semplon** [comment]
see this image
image

the indentation if your modified <li> are too much to right. it's not aligned properly.

**Comment by vdanelia** [comment]
Ah ok :)

**Comment by semplon** [comment]
this is how to set at notepad++
http://superuser.com/questions/48039/where-is-the-tab-indent-options-in-notepad-5-5

**Pull request merged**
